#!/bin/bash
# Copyright 2018 The Chromium OS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

# This files wraps lld.

exec "$(readlink -f "$0").real" --no-rosegment -z now -z relro --hash-style=gnu "$@"
