# Copyright 2021 The ChromiumOS Authors
# Distributed under the terms of the GNU General Public License v2

EAPI="7"

CROS_RUST_REMOVE_DEV_DEPS=1

inherit cros-rust

DESCRIPTION='Automatically generates Rust FFI bindings to C and C++ libraries.'
HOMEPAGE='https://rust-lang.github.io/rust-bindgen/'
SRC_URI="https://crates.io/api/v1/crates/${PN}/${PV}/download -> ${P}.crate"

LICENSE="BSD"
SLOT="0/${PVR}"
KEYWORDS="*"

DEPEND="dev-rust/third-party-crates-src:="
RDEPEND="${DEPEND}"

# This file was automatically generated by cargo2ebuild.py
# Manual additions.
src_compile() {
	ecargo_build
}

src_install() {
	cros-rust_src_install
	dobin "$(cros-rust_get_build_dir)/bindgen"
}
