# Copyright 2021 The ChromiumOS Authors
# Distributed under the terms of the GNU General Public License v2

EAPI="7"

CROS_RUST_REMOVE_DEV_DEPS=1
CROS_RUST_REMOVE_TARGET_CFG=1

inherit cros-rust

DESCRIPTION="Rustyline, a readline implementation based on Antirez's Linenoise"
HOMEPAGE='https://crates.io/crates/rustyline'
SRC_URI="https://crates.io/api/v1/crates/${PN}/${PV}/download -> ${P}.crate"

LICENSE="MIT"
SLOT="${PV}/${PR}"
KEYWORDS="*"

DEPEND="
	dev-rust/third-party-crates-src:=
	=dev-rust/log-0.4*
	=dev-rust/radix_trie-0.2*
	>=dev-rust/smallvec-1.6.1 <dev-rust/smallvec-2.0.0_alpha
	=dev-rust/skim-0.9*
"
RDEPEND="${DEPEND}"

# This file was automatically generated by cargo2ebuild.py

RESTRICT="test"
