# Copyright 2022 The ChromiumOS Authors
# Distributed under the terms of the GNU General Public License v2

EAPI="7"

CROS_RUST_REMOVE_DEV_DEPS=1

inherit cros-rust

DESCRIPTION='Provides a crate with information from the time it was built.'
HOMEPAGE='https://crates.io/crates/built'
SRC_URI="https://crates.io/api/v1/crates/${PN}/${PV}/download -> ${P}.crate"

LICENSE="MIT"
SLOT="${PV}/${PR}"
KEYWORDS="*"

DEPEND="
	dev-rust/third-party-crates-src:=
	=dev-rust/cargo-lock-7*
	=dev-rust/chrono-0.4*
"
RDEPEND="${DEPEND}"

# This file was automatically generated by cargo2ebuild.py
