# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: audio_config.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='audio_config.proto',
  package='audio',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x12\x61udio_config.proto\x12\x05\x61udio\"E\n\x0b\x41udioConfig\x12\x19\n\x11\x64\x65vice_config_dir\x18\x01 \x01(\t\x12\x1b\n\x13internal_ucm_suffix\x18\x02 \x01(\tb\x06proto3')
)




_AUDIOCONFIG = _descriptor.Descriptor(
  name='AudioConfig',
  full_name='audio.AudioConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='device_config_dir', full_name='audio.AudioConfig.device_config_dir', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='internal_ucm_suffix', full_name='audio.AudioConfig.internal_ucm_suffix', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=29,
  serialized_end=98,
)

DESCRIPTOR.message_types_by_name['AudioConfig'] = _AUDIOCONFIG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AudioConfig = _reflection.GeneratedProtocolMessageType('AudioConfig', (_message.Message,), dict(
  DESCRIPTOR = _AUDIOCONFIG,
  __module__ = 'audio_config_pb2'
  # @@protoc_insertion_point(class_scope:audio.AudioConfig)
  ))
_sym_db.RegisterMessage(AudioConfig)


# @@protoc_insertion_point(module_scope)
