# Copyright 2022 The ChromiumOS Authors
# Distributed under the terms of the GNU General Public License v2

EAPI="7"

CROS_RUST_REMOVE_DEV_DEPS=1

inherit cros-rust

DESCRIPTION='Logger that logs to stderr based on verbosity specified'
HOMEPAGE='https://github.com/cardoe/stderrlog-rs'
SRC_URI="https://crates.io/api/v1/crates/${PN}/${PV}/download -> ${P}.crate"

LICENSE="|| ( MIT Apache-2.0 )"
SLOT="${PV}/${PR}"
KEYWORDS="*"

DEPEND="
	dev-rust/third-party-crates-src:=
	>=dev-rust/chrono-0.4.10 <dev-rust/chrono-0.5.0_alpha
	>=dev-rust/log-0.4.11 <dev-rust/log-0.5.0_alpha
	=dev-rust/thread_local-1.1*
"
RDEPEND="${DEPEND}"

# This file was automatically generated by cargo2ebuild.py
