# Copyright 2021 The Chromium OS Authors. All rights reserved.
# Distributed under the terms of the GNU General Public License v2

EAPI="7"

CROS_RUST_REMOVE_DEV_DEPS=1
CROS_RUST_REMOVE_TARGET_CFG=1

inherit cros-rust

DESCRIPTION='Safe abstractions for accessing the VM physical memory'
HOMEPAGE='https://crates.io/crates/vm-memory'
SRC_URI="https://crates.io/api/v1/crates/${PN}/${PV}/download -> ${P}.crate"

LICENSE="|| ( Apache-2.0 BSD )"
SLOT="${PV}/${PR}"
KEYWORDS="*"

DEPEND="
	>=dev-rust/arc-swap-0.4.5:=
	>=dev-rust/libc-0.2.39:=
"
RDEPEND="${DEPEND}"

# This file was automatically generated by cargo2ebuild.py
