# Copyright 2021 The Chromium OS Authors. All rights reserved.
# Distributed under the terms of the GNU General Public License v2

EAPI="7"

CROS_RUST_REMOVE_DEV_DEPS=1

inherit cros-rust

DESCRIPTION="A simple to use, efficient, and full-featured Command Line Argument Parser"
HOMEPAGE="https://clap.rs/"
SRC_URI="https://crates.io/api/v1/crates/${PN}/${PV}/download -> ${P}.crate"

LICENSE="MIT"
SLOT="${PV}/${PR}"
KEYWORDS="*"

DEPEND="
	>=dev-rust/atty-0.2.2:= <dev-rust/atty-0.3.0
	=dev-rust/bitflags-1*:=
	~dev-rust/clippy-0.0.166:=
	=dev-rust/strsim-0.8*:=
	=dev-rust/term_size-0.3*:=
	=dev-rust/textwrap-0.11*:=
	>=dev-rust/unicode-width-0.1.4:= <dev-rust/unicode-width-0.2.0
	=dev-rust/vec_map-0.8*:=
	=dev-rust/yaml-rust-0.3*:=
	=dev-rust/ansi_term-0.11*:=
"
RDEPEND="${DEPEND}"

# This file was automatically generated by cargo2ebuild.py
