# Copyright 2021 The Chromium OS Authors. All rights reserved.
# Distributed under the terms of the GNU General Public License v2

EAPI="7"

CROS_RUST_REMOVE_DEV_DEPS=1

inherit cros-rust

DESCRIPTION='encodes and decodes base64 as bytes or utf8'
HOMEPAGE='https://crates.io/crates/base64'
SRC_URI="https://crates.io/api/v1/crates/${PN}/${PV}/download -> ${P}.crate"

LICENSE="|| ( MIT Apache-2.0 )"
SLOT="${PV}/${PR}"
KEYWORDS="*"

DEPEND="
	>=dev-rust/byteorder-1.2.6:= <dev-rust/byteorder-2.0.0
"
RDEPEND="${DEPEND}"

# This file was automatically generated by cargo2ebuild.py

# Test phase is disabled due to the "trait objects without an explicit
# `dyn` are deprecated" error in src/decode.rs:58.
RESTRICT="test"
