# Copyright 2022 The ChromiumOS Authors
# Distributed under the terms of the GNU General Public License v2

EAPI="7"

CROS_RUST_REMOVE_DEV_DEPS=1
CROS_RUST_REMOVE_TARGET_CFG=1

inherit cros-rust

DESCRIPTION='Low-level bindings to the system libz library (also known as zlib).'
HOMEPAGE='https://crates.io/crates/libz-sys'
SRC_URI="https://crates.io/api/v1/crates/${PN}/${PV}/download -> ${P}.crate"

LICENSE="|| ( MIT Apache-2.0 )"
SLOT="${PV}/${PR}"
KEYWORDS="*"

DEPEND="
	>=dev-rust/libc-0.2.43 <dev-rust/libc-0.3.0_alpha
	>=dev-rust/cc-1.0.18 <dev-rust/cc-2.0.0_alpha
	>=dev-rust/cmake-0.1.44 <dev-rust/cmake-0.2.0_alpha
	>=dev-rust/pkg-config-0.3.9 <dev-rust/pkg-config-0.4.0_alpha
"
RDEPEND="${DEPEND}"

# This file was automatically generated by cargo2ebuild.py
